package com.wadpam.rnr.dao;

import com.google.appengine.api.datastore.Key;
import com.wadpam.rnr.domain.DAppSettings;

/**
 * Business Methods interface for entity DAppSettings.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-07T22:42:53.285+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DAppSettingsDao extends GeneratedDAppSettingsDao<Key, Key> {

    /** Get a domain object by a GAE datastore key
     * @param key GAE datastore key
     * @return an app settings domain object if key exists in the datastore
     */
    public DAppSettings findByCorePrimaryKey(Key key);

}
