package com.wadpam.rnr.dao;

import com.google.appengine.api.NamespaceManager;
import com.wadpam.rnr.domain.DApp;

/**
 * Implementation of Business Methods related to entity DAppAdmin.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-11T21:01:04.040+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DAppAdminDaoBean 
	extends GeneratedDAppAdminDaoImpl
		implements DAppAdminDao 
{

    // Default constructor to enable caching by Mardao
    public DAppAdminDaoBean() {
        //this.memCacheEntity = true;
        //this.memCacheAll = true;
    }


}
