package com.wadpam.rnr.dao;

/**
 * Implementation of Business Methods related to entity DAppSettings.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-09T07:48:57.528+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DAppSettingsDaoBean 
	extends GeneratedDAppSettingsDaoImpl
		implements DAppSettingsDao 
{

    // Default constructor to enable caching by Mardao
    public DAppSettingsDaoBean() {
        this.memCacheEntities = true;
        this.memCacheAll = true;
    }
}
