package com.wadpam.rnr.dao;

import com.google.appengine.api.datastore.Key;
import com.wadpam.rnr.domain.DAppSettings;

/**
 * Implementation of Business Methods related to entity DAppSettings.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-07T22:42:53.285+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DAppSettingsDaoBean 
	extends GeneratedDAppSettingsDaoImpl
		implements DAppSettingsDao 
{

    // Get a domain object by a GAE datastore key
    @Override
    public DAppSettings findByCorePrimaryKey(Key key) {
        return findByPrimaryKey(key.getName());
    }
}
