package com.wadpam.rnr.dao;

import com.google.appengine.api.datastore.*;
import com.wadpam.rnr.domain.DComment;
import net.sf.mardao.core.CursorPage;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;

/**
 * Implementation of Business Methods related to entity DComment.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-05T20:54:54.772+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DCommentDaoBean 
	extends GeneratedDCommentDaoImpl
		implements DCommentDao 
{

    // Create datastore key
    @Override
    public Key createKey(Long id) {
        return createKey(id);
    }


}
