package com.wadpam.rnr.dao;

/**
 * Implementation of Business Methods related to entity DFavorites.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-04T17:31:55.012+0200.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DFavoritesDaoBean 
	extends GeneratedDFavoritesDaoImpl
		implements DFavoritesDao 
{

	// TODO: implement your Business Methods here

}
