package com.wadpam.rnr.dao;

import com.google.appengine.api.datastore.Key;

/**
 * Business Methods interface for entity DFavorites.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-05T20:54:54.772+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DFavoritesDao extends GeneratedDFavoritesDao<Key, Key> {
}
