package com.wadpam.rnr.dao;

import com.google.appengine.api.datastore.Key;
import com.wadpam.rnr.domain.DFavorites;

/**
 * Implementation of Business Methods related to entity DFavorites.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-05T20:54:54.772+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DFavoritesDaoBean 
	extends GeneratedDFavoritesDaoImpl
		implements DFavoritesDao 
{
    // Default constructor to enable caching by Mardao
    public DFavoritesDaoBean() {
        //this.memCacheEntity = true;
        //this.memCacheAll = false;
    }

}
