package com.wadpam.rnr.dao;

/**
 * Implementation of Business Methods related to entity DLike.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-01T20:20:31.614+0200.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DLikeDaoBean 
	extends GeneratedDLikeDaoImpl
		implements DLikeDao 
{

	// TODO: implement your Business Methods here

}
