package com.wadpam.rnr.dao;

import com.google.appengine.api.datastore.Key;

/**
 * Business Methods interface for entity DLike.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-07-24T23:26:21.459+0200.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DLikeDao extends GeneratedDLikeDao<Key, Key> {

	// TODO: declare your Business Methods here
	
}
