package com.wadpam.rnr.dao;

/**
 * Implementation of Business Methods related to entity DOfficer.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-21T21:32:09.943+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DOfficerDaoBean 
	extends GeneratedDOfficerDaoImpl
		implements DOfficerDao 
{

    // Default constructor to enable caching by Mardao
    public DOfficerDaoBean() {
        //this.memCacheEntity = true;
        //this.memCacheAll = true;
    }
}
