package com.wadpam.rnr.dao;

import com.google.appengine.api.datastore.Key;

/**
 * Business Methods interface for entity DProduct.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-07-27T22:34:42.220+0200.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DProductDao extends GeneratedDProductDao<Key, Key> {

	// TODO: declare your Business Methods here
	
}
