package com.wadpam.rnr.dao;

import com.wadpam.rnr.domain.DProduct;

import java.io.Serializable;

import com.wadpam.rnr.service.RnrService;
import net.sf.mardao.core.CursorPage;

/**
 * Business Methods interface for entity DProduct.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-05T20:54:54.772+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DProductDao extends GeneratedDProductDao {


    /**
     * Find most liked products
     * @param limit the number of products to max return
     * @param cursorKey A cursor from a previous query or null if this is the first page
     * @return A list of products sorted according to the number of likes
     */
    public CursorPage<DProduct, String> queryMostLiked(int limit, Serializable cursorKey);

    /**
     * Find most thumbs up products
     * @param limit the number of products to max return
     * @param cursorKey A cursor from a previous query or null if this is the first page
     * @return A list of products sorted according to the number of thumbs up
     */
    public CursorPage<DProduct, String> queryMostThumbsUp(int limit, Serializable cursorKey);

    /**
     * Find most thumbs up products
     * @param limit the number of products to max return
     * @param cursorKey A cursor from a previous query or null if this is the first page
     * @return A list of products sorted according to the number of thumbs down
     */
    public CursorPage<DProduct, String> queryMostThumbsDown(int limit, Serializable cursorKey);


    /**
     * Find most commented products
     * @param limit the number of products to max return
     * @param cursorKey A cursor from a previous query or null if this is the first page
     * @return A list of products sorted according to the number of comments
     */
    public CursorPage<DProduct, String> queryMostCommented(int limit, Serializable cursorKey);

    /**
     * Find most rated products
     * @param limit the number of product to max return
     * @param cursorKey A cursor from a previous query or null if this is the first page
     * @return A list of products sorted according to the number of ratings
     */
    public CursorPage<DProduct, String> queryMostRated(int limit, Serializable cursorKey);

    /**
     * Find products with highest average rating
     * @param limit the number of product to max return
     * @param cursorKey A cursor from a previous query or null if this is the first page
     * @return A list of products sorted according to average rating
     */
    public CursorPage<DProduct, String> queryTopRated(int limit, Serializable cursorKey);

    /**
     * Get nearby products
     * @param pageSize the number of products to return
     * @param cursor the cursor returned from the previous call to this method. If this is the first call, use null.
     * @param latitude the latitude to search around
     * @param longitude the longitude to search around
     * @param radius the radius to search within
     * @param sortOrder the sort order of the returned result
     * @return a new cursor that can be used to get the next products.
     */
    public CursorPage<DProduct, String> searchForNearby(int pageSize, String cursor, Float latitude, Float longitude,
                                                        int radius, RnrService.SortOrder sortOrder);

}
