package com.wadpam.rnr.dao;

import com.wadpam.rnr.domain.DQuestion;
import net.sf.mardao.core.CursorPage;

/**
 * Business Methods interface for entity DQuestion.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-02-11T09:17:50.907+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DQuestionDao extends GeneratedDQuestionDao {

    /**
     * Find all questions assigned to user matching the provided parameters.
     * @param username return questions assigned tot his user
     * @param answerState optional. only return questions matching answer state
     *                    1 - unanswered
     *                    2 - answered
     *                    If no value is provided, both types will be returned
     * @param productId optional. Only return questions for this product id
     * @return A page of questions
     */
    public Iterable<DQuestion> queryByTargetUsernameAnswerStateProductId(
            String username,
            Integer answerState,
            String productId);

    /**
     * Find all questions asked by a specific user that match the provided product id.
     * @param opUsername the original posters user name
     * @param productId optional. Only return questions for this product id
     * @return
     */
    public Iterable<DQuestion> queryByOpUsernameProductId(String opUsername, String productId);
}
