package com.wadpam.rnr.dao;

import com.wadpam.rnr.domain.DRating;
import java.util.Collection;
import net.sf.mardao.api.dao.Expression;

/**
 * Implementation of Business Methods related to entity DRating.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-05-31T19:50:34.960+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DRatingDaoBean 
	extends GeneratedDRatingDaoImpl
		implements DRatingDao 
{

    @Override
    public Collection<DRating> findGeoBase(String orderBy, boolean ascending, int limit, int offset, Expression... filters) {
        return findGeoBase(orderBy, ascending, limit, offset, filters);
    }

    @Override
    public String getGeoboxesColumnName() {
        return COLUMN_NAME_GEOBOXES;
    }

    @Override
    public Collection<DRating> findInGeobox(float lat, float lng, int resolution, int slice, String orderBy, boolean ascending, int offset, int limit, Expression... filters) {
        throw new UnsupportedOperationException("Invoke on GeoDao instead.");
    }

}
