package com.wadpam.rnr.dao;

/**
 * Implementation of Business Methods related to entity DRating.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-05-31T19:50:34.960+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DRatingDaoBean 
	extends GeneratedDRatingDaoImpl
		implements DRatingDao 
{

	// TODO: implement your Business Methods here

}
