package com.wadpam.rnr.dao;

import com.google.appengine.api.datastore.Key;
import com.wadpam.rnr.domain.DRating;

/**
 * Business Methods interface for entity DRating.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-05T20:54:54.772+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DRatingDao extends GeneratedDRatingDao<Key, Key> {

    /**
     * Find ratings done by a specific user and a specific product.
     * @param productId the product
     * @param username the user
     * @return a rating
     */
    public DRating findByProductIdUsername(String productId, String username);
}
