package com.wadpam.rnr.dao;

import com.google.appengine.api.datastore.Key;

/**
 * Business Methods interface for entity DResult.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-05-31T20:44:38.277+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DResultDao extends GeneratedDResultDao<Key, Key> {

	// TODO: declare your Business Methods here
	
}
