package com.wadpam.rnr.dao;

/**
 * Implementation of Business Methods related to entity DResult.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-05-31T20:44:38.277+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DResultDaoBean 
	extends GeneratedDResultDaoImpl
		implements DResultDao 
{

	// TODO: implement your Business Methods here

}
