package com.wadpam.rnr.dao;

import com.wadpam.rnr.domain.DThumbs;
import net.sf.mardao.core.Filter;

/**
 * Implementation of Business Methods related to entity DThumbs.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-22T12:45:10.581+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DThumbsDaoBean 
	extends GeneratedDThumbsDaoImpl
		implements DThumbsDao 
{

    @Override
    // Find thumbs done by user on product
    public DThumbs findByProductIdUsername(String productId, String username) {
        final Filter filter1 = createEqualsFilter(COLUMN_NAME_PRODUCTID, productId);
        final Filter filter2 = createEqualsFilter(COLUMN_NAME_USERNAME, username);

        return findUniqueBy(filter1, filter2);
    }
}
